### ISSUE TITLE
Can’t login or reset password 

### ISSUE THREAD

**Issue by dgcaste** [teslabout/teslabout-bug-tracker#10]
Was out for the holidays. Now I can’t log in or reset my password.

**Comment by joeypoon** [comment]
@dgcaste what error are you seeing? we had an issue with old frontend files being served which turned out to be cached from cloudflare. we mitigated this but might need a cache clear to resolve locally.

**Comment by dgcaste** [comment]
The reset password page is just a login page. 

Daniel

**Comment by joeypoon** [comment]
@dgcaste I triggered a reset manually for you. Let me know if you got the email. The reset link in the email itself will expire in 30 minutes. Checking the logs, I don't see any resets triggered with the email I just triggered it on. Is it the same email you attempted with?

**Comment by dgcaste** [comment]
That worked. Thanks!

Daniel
