### ISSUE TITLE
Vehicle color inaccurate

### ISSUE THREAD

**Issue by dgcaste** [teslabout/teslabout-bug-tracker#2]
I think the API has access to this data so the color should ideally match.

**Comment by jjsoviet** [comment]
@dgcaste is your vehicle by any chance a Tesla Model 3? If I remember correctly, the API is incorrectly returning a default set of option codes which default it to the black model.

Unfortunately we didn't have a different vehicle to test it on while we were developing this app, so we actually are unaware if the issue extends to Model S and Model X units.

**Comment by dgcaste** [comment]
I have a Pearl White Model 3 Performance, built in September 2019, with HW 3.0 verified and no FSD. I don’t have my PC with me to study my API response and to find if there’s a way to interpret the data.

**Comment by jjsoviet** [comment]
Got it, that makes sense - we have another tester with a Model 3 and his also returns the same image: a Model 3 in Obsidian Black and 19" Sport wheels. Seems like the API is providing the same codes for Model 3 owners regardless of specifics. We should definitely take a look at this however!

**Comment by joeypoon** [comment]
@jjsoviet We do get the actual color/wheels on the vehicle's data so we can map them back to the correct option codes.

**Comment by joeypoon** [comment]
@dgcaste you probably noticed this already but we've made some updates to make color/wheels more accurate. This doesn't quite handle some of the legacy colors/wheels but should improve for the majority.
